[phases.setup]
nixPkgs = ['nodejs-18_x', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = ['npm ci --legacy-peer-deps']

[phases.build]
cmds = ['npm rebuild better-sqlite3 --build-from-source']

[start]
cmd = 'node server.js'
